const CallCenterActionTypes = {
  GET_CALL_CENTER_START: 'GET_CALL_CENTER_START',
  GET_CALL_CENTER_SUCCESS: 'GET_CALL_CENTER_SUCCESS',
  GET_CALL_CENTER_FAILURE: 'GET_CALL_CENTER_FAILURE',
};
export default CallCenterActionTypes;
